// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDumqsXz8PPTkWBcqgH5l7G3qdJmhql9FE',
    appId: '1:600208161651:web:a099a609d25ce7b37e2306',
    messagingSenderId: '600208161651',
    projectId: 'smartflow-37390',
    authDomain: 'smartflow-37390.firebaseapp.com',
    storageBucket: 'smartflow-37390.firebasestorage.app',
    measurementId: 'G-2Q5HSYRL2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeyGnN9v4LstM2zubWrGWqP_oPOyN4bk',
    appId: '1:600208161651:android:c9e83c7ccbb45a6d7e2306',
    messagingSenderId: '600208161651',
    projectId: 'smartflow-37390',
    storageBucket: 'smartflow-37390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_2J4VBejkZ9P6Tsfq67b-S38m9KkwD4',
    appId: '1:600208161651:ios:fce1e8376987447f7e2306',
    messagingSenderId: '600208161651',
    projectId: 'smartflow-37390',
    storageBucket: 'smartflow-37390.firebasestorage.app',
    iosBundleId: 'com.example.smartflowTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_2J4VBejkZ9P6Tsfq67b-S38m9KkwD4',
    appId: '1:600208161651:ios:fce1e8376987447f7e2306',
    messagingSenderId: '600208161651',
    projectId: 'smartflow-37390',
    storageBucket: 'smartflow-37390.firebasestorage.app',
    iosBundleId: 'com.example.smartflowTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDumqsXz8PPTkWBcqgH5l7G3qdJmhql9FE',
    appId: '1:600208161651:web:26b7fedf95f3b0b67e2306',
    messagingSenderId: '600208161651',
    projectId: 'smartflow-37390',
    authDomain: 'smartflow-37390.firebaseapp.com',
    storageBucket: 'smartflow-37390.firebasestorage.app',
    measurementId: 'G-FC0HBFYBF2',
  );
}
